/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package pos.pro;



import java.awt.event.KeyEvent;
//import java.io.File;
import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
//import java.util.HashMap;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.view.JasperViewer;
import java.sql.PreparedStatement;
//import javax.print.PrintService;
//import java.awt.print.Printable;
//import java.awt.print.PrinterException;
//import java.awt.print.PrinterJob;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
//import javax.print.PrintServiceLookup;
//import javax.print.attribute.HashPrintRequestAttributeSet;
//import javax.print.attribute.PrintRequestAttributeSet;
//import javax.print.attribute.standard.Copies;
//import net.sf.jasperreports.engine.JasperPrintManager;


/**
 *
 * @author Liamani
 */
public class Sales extends javax.swing.JPanel {

    
    public static String barcode_c = "0";
    public static String cus_id = "0";
    public static String select_pro_name = null;
    public Double stockqty = 0.0;
    private String uname;
    
    public Sales(String loggedInUser) {
        initComponents();
        data_load();
        this.uname = loggedInUser;
    }
    
    
    public void data_load() {

    try {
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM customers");
        Vector vCustomers = new Vector();

        while (rs.next()) {
            vCustomers.add(rs.getString("customer_name"));
        }

        DefaultComboBoxModel comCustomers = new DefaultComboBoxModel(vCustomers);
        combo_customer.setModel(comCustomers);
    } catch (SQLException e) {
        System.out.println(e);
    }

    try {
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM products");
        Vector vProducts = new Vector();

        while (rs.next()) {
            vProducts.add(rs.getString("product_name"));
        }

        DefaultComboBoxModel comProducts = new DefaultComboBoxModel(vProducts);
        combo_product.setModel(comProducts);
    } catch (SQLException e) {
        System.out.println(e);
    }

    try {
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery("SELECT * FROM extra WHERE exid = 1");

        if (rs.next()) {
            inid.setText(rs.getString("val"));
        }
    } catch (SQLException e) {
        System.out.println(e);
    }

    try {
        String inidText = inid.getText();
        if (!inidText.isEmpty()) {
            int i = Integer.parseInt(inidText);
            i++;
            inid.setText(String.valueOf(i));
        } else {
            // Handle the case where inidText is empty
            System.out.println("inidText is empty");
        }
    } catch (NumberFormatException e) {
        // Handle the case where inidText is not a valid integer
        System.out.println(e);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    
public void calculateProduct() {
    double quantity = Double.parseDouble(pro_qty.getText());
    double price = Double.parseDouble(unit_price.getText());
    double total = quantity * price;
    tot_price.setText(String.valueOf(total));
}
    
    
public void calculateCartTotal() {
    int numOfRows = jTable1.getRowCount();
    double totalPrice = 0;
    double totalQuantity = 0;

    for (int i = 0; i < numOfRows; i++) {
        double value = Double.parseDouble(jTable1.getValueAt(i, 5).toString());
        double quantity = Double.parseDouble(jTable1.getValueAt(i, 3).toString());
        totalPrice += value;
        totalQuantity += quantity;
    }

    total_price.setText(Double.toString(totalPrice));
    total_qty.setText(Double.toString(totalQuantity));
}
    
    
public void balance() {
    try {
        Double paid = Double.valueOf(paid_amount.getText());
        Double total = Double.valueOf(total_price.getText());
        Double due = paid - total;
        balance.setText(String.valueOf(due));
    } catch (NullPointerException e) {
        System.err.println("NullPointerException occurred: " + e.getMessage());
    } catch (NumberFormatException e) {
        System.err.println("NumberFormatException occurred: " + e.getMessage());
    }
}
    
    
public void stckload() {
    DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
    int rc = tb.getRowCount();
    for (int i = 0; i < rc; i++) {
        String bcode = tb.getValueAt(i, 2).toString();
        String qty = tb.getValueAt(i, 3).toString();

        try {
            Connection con = db.mycon();
            PreparedStatement stmt = con.prepareStatement("SELECT qty FROM products WHERE bar_code = ?");
            stmt.setString(1, bcode);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                Double stockquantity;
                stockquantity = Double.valueOf(rs.getString("qty"));
                Double sell_qty = Double.valueOf(qty);
                Double new_qty = stockquantity - sell_qty;
                String newquantity = String.valueOf(new_qty);

                PreparedStatement updateStmt = con.prepareStatement("UPDATE products SET qty = ? WHERE bar_code = ?");
                updateStmt.setString(1, newquantity);
                updateStmt.setString(2, bcode);
                updateStmt.executeUpdate();
            }

        } catch (NumberFormatException | SQLException e) {
            System.out.println(e);
        }
    }
}
    
public void addDataToTable() {
    String stockQtyText = stk_qty.getText();
    String sellQtyText = pro_qty.getText();

    if (stockQtyText.isEmpty() || sellQtyText.isEmpty()) {
        JOptionPane.showMessageDialog(paid_amount, "من فضلك أدخل رقما صحيحا");
        return;
    }

    double stockQty = Double.parseDouble(stockQtyText);
    double sellQty = Double.parseDouble(sellQtyText);

    if (sellQty <= stockQty) {
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        Vector<Object> rowData = new Vector<>();
        rowData.add(inid.getText());
        //rowData.add(combo_product.getSelectedItem().toString());
        rowData.add(select_pro_name);
        rowData.add(bar_c.getText());
        rowData.add(pro_qty.getText());
        rowData.add(unit_price.getText());
        rowData.add(tot_price.getText());

        tableModel.addRow(rowData);
        calculateCartTotal();
    } else {
        JOptionPane.showMessageDialog(paid_amount, "المخزون فيه " + stockQty);
    }
}

private void resetBarcodeScanner() {
    barcode_scanner.setText("");
    barcode_scanner.requestFocus();
}


public void printBill() {
    try {
        AutoPrintBill autoPrintBill = new AutoPrintBill();
        StringBuilder billContent = new StringBuilder();

        // Store information
        billContent.append("متجر أسامة يرحب بكم\nحي العربي بن مهيدي, عين تموشنت, المالح\n+21364525899\n");
        billContent.append("----------------------------------------------------------------\n");

        // Table header
        billContent.append(" السلعة \tالكمية \tالسعر \tالسعر الإجمالي \n");
        billContent.append("----------------------------------------------------------------\n");

        // Populate billContent from jTable1
        DefaultTableModel df = (DefaultTableModel) jTable1.getModel();
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            String name = df.getValueAt(i, 1).toString();
            String qty = df.getValueAt(i, 3).toString();
            String unip = df.getValueAt(i, 4).toString();
            String totr = df.getValueAt(i, 5).toString();

            billContent.append(String.format("%s\t%s\t%s\t%s\n", name, qty, unip, totr));
        }

        // Bill summary
        billContent.append("----------------------------------------------------------------\n");
        billContent.append("الفاتورة:\t").append(total_price.getText()).append("د.ج\n");
        billContent.append("المبلغ المدفوع:\t").append(paid_amount.getText()).append("د.ج\n");
        billContent.append("الفرق :\t").append(balance.getText()).append("د.ج\n");
        billContent.append("====================================\n");
        billContent.append("شكرا على تعاملكم معنا ...\n");
        billContent.append("----------------------------------------------------------------\n");
        billContent.append("Software by LIAMANI\n");

        autoPrintBill.setBillContent(billContent.toString());
        autoPrintBill.printBill();
    } catch (Exception e) {
        // Handle exceptions here
        e.printStackTrace();
    }
}











    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inid = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bill = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unit_price = new javax.swing.JLabel();
        combo_product = new javax.swing.JComboBox<>();
        barcode_scanner = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tot_price = new javax.swing.JLabel();
        bar_c = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        combo_customer = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        stk_qty = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        pro_qty = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        paid_amount = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        total_price = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        balance = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        total_qty = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("فاتورة رقم");

        inid.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        inid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        inid.setText("01");

        jLabel18.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText(":");

        bill.setEditable(false);
        bill.setColumns(20);
        bill.setRows(5);
        jScrollPane2.setViewportView(bill);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(inid, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inid)
                    .addComponent(jLabel18))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/r.png"))); // NOI18N
        jLabel2.setText("سلعة");

        jLabel3.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("سعر الوحدة");

        jLabel4.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("كمية");

        unit_price.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        unit_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        unit_price.setText("00.00");

        combo_product.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_product.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختار", "" }));
        combo_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_productActionPerformed(evt);
            }
        });
        combo_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                combo_productKeyReleased(evt);
            }
        });

        barcode_scanner.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        barcode_scanner.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        barcode_scanner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barcode_scannerKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText(":");

        jLabel10.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText(":");

        jLabel11.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText(":");

        jLabel5.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/barcode_3396275 (1).png"))); // NOI18N
        jLabel5.setText("الباركود");

        jLabel19.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText(":");

        tot_price.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        tot_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tot_price.setText("00.00");

        bar_c.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        bar_c.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bar_c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/barcode_25350 (1).png"))); // NOI18N
        bar_c.setText("Code bar");

        jLabel17.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/z.png"))); // NOI18N
        jLabel17.setText("زبون");

        jLabel20.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText(":");

        combo_customer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        combo_customer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "اختار", " " }));
        combo_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_customerActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/ready_5867537 (1).png"))); // NOI18N
        jLabel21.setText("كمية في المخزون");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText(":");

        stk_qty.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        stk_qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stk_qty.setText("00.00");

        jLabel23.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("السعر الإجمالي");

        jLabel24.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText(":");

        pro_qty.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        pro_qty.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pro_qty.setText("1");
        pro_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                pro_qtyKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pro_qtyKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(unit_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tot_price, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(pro_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(stk_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                .addGap(94, 94, 94)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(barcode_scanner, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(combo_product, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(125, 125, 125)
                .addComponent(combo_customer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(bar_c, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel17)
                                .addComponent(combo_customer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel20)
                                .addComponent(jLabel4)
                                .addComponent(jLabel10))
                            .addComponent(pro_qty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(stk_qty)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(combo_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(barcode_scanner, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tot_price)
                                .addComponent(jLabel19))
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(unit_price)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bar_c)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTable1.setFont(new java.awt.Font("Janna LT", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "INID", "السلعة", "Code Bar", "الكمية", "سعر الوحدة", "السعر الكلي"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setFont(new java.awt.Font("Janna LT", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/plus_1828817 (2).png"))); // NOI18N
        jButton1.setText("أضف إلى السلة");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Janna LT", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/s.png"))); // NOI18N
        jButton2.setText("حذف");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Janna LT", 0, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/two_10093458 (1).png"))); // NOI18N
        jButton3.setText("حذف الكل");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paid_amount.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        paid_amount.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paid_amount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                paid_amountKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("المبلغ المدفوع");

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("المبلغ الكلي");

        total_price.setBackground(new java.awt.Color(30, 249, 86));
        total_price.setFont(new java.awt.Font("Janna LT", 1, 24)); // NOI18N
        total_price.setForeground(new java.awt.Color(40, 42, 54));
        total_price.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total_price.setText("00.00");
        total_price.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        total_price.setOpaque(true);

        jLabel13.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("الفرق");

        jLabel15.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText(":");

        balance.setBackground(new java.awt.Color(255, 51, 51));
        balance.setFont(new java.awt.Font("Janna LT", 1, 24)); // NOI18N
        balance.setForeground(new java.awt.Color(40, 42, 54));
        balance.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        balance.setText("00.00");
        balance.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        balance.setOpaque(true);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(total_price, javax.swing.GroupLayout.DEFAULT_SIZE, 355, Short.MAX_VALUE)
                    .addComponent(balance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(total_price)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(balance)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText(":");

        jLabel8.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("الكمية الإجمالية");

        jLabel16.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText(":");

        total_qty.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        total_qty.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total_qty.setText("00");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(total_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(paid_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel16)
                        .addComponent(total_qty))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(paid_amount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(110, 110, 110))
        );

        jButton4.setBackground(new java.awt.Color(248, 248, 242));
        jButton4.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(40, 42, 54));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/donation_872789 (1).png"))); // NOI18N
        jButton4.setText("دفع ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(248, 248, 242));
        jButton5.setFont(new java.awt.Font("Janna LT", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(40, 42, 54));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pos/pro/img/printer_1497542 (1).png"))); // NOI18N
        jButton5.setText("طبع الفاتورة");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void combo_productActionPerformed(java.awt.event.ActionEvent evt) {
    String name = combo_product.getSelectedItem().toString();
    
    try {
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery("SELECT bar_code,sell_price,qty,product_name FROM products WHERE product_name ='" + name + "'");
        if (rs.next()) {
            unit_price.setText(rs.getString("sell_price"));
            bar_c.setText(rs.getString("bar_code"));
            stk_qty.setText(rs.getString("qty"));
            select_pro_name = rs.getString("product_name");
        }
        
    } catch (SQLException e) {
        System.out.println(e);
    }
    
    pro_qty.setText("");
    pro_qty.requestFocus();
}

private void barcode_scannerKeyReleased(java.awt.event.KeyEvent evt) {
    // Barcode scanner
    String brcode = barcode_scanner.getText();
    
    try {
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery("SELECT bar_code, sell_price, qty, product_name FROM products WHERE bar_code ='" + brcode + "'");
        if (rs.next()) {
            unit_price.setText(rs.getString("sell_price"));
            bar_c.setText(rs.getString("bar_code"));
            stk_qty.setText(rs.getString("qty"));
            select_pro_name = rs.getString("product_name");

            
//            Vector<String> v = new Vector<>();
//            v.add(rs.getString("product_name"));
//            combo_product.setModel(new DefaultComboBoxModel<>(v));
        }
        pro_qty.setText("1");
        pro_qty.requestFocus();
    } catch (SQLException e) {
        System.out.println(e);
    }
}

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // add to cart
       addDataToTable();  
        
    }//GEN-LAST:event_jButton1ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int selectedRow = jTable1.getSelectedRow();
        
        if (selectedRow != -1) {
            tb.removeRow(selectedRow);
        }
        
    } catch (Exception e) {
        System.out.println(e);
    }
    
    calculateCartTotal();
}

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
    DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
    tb.setRowCount(0);
    calculateCartTotal();
}

private void paid_amountKeyReleased(java.awt.event.KeyEvent evt) {
    balance();
}

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    
    Double tprice = Double.valueOf(total_price.getText());
    if (tprice == 0) {
        JOptionPane.showMessageDialog(paid_amount, "لا يوجد أي سلعة في السلة");
    }
    else{
    try {
        DefaultTableModel tb = (DefaultTableModel) jTable1.getModel();
        int rc = tb.getRowCount();
        for (int i = 0; i < rc; i++) {
            String invoice_id;
            invoice_id = tb.getValueAt(i, 0).toString();
            String P_name = tb.getValueAt(i, 1).toString();
            String b_code = tb.getValueAt(i, 2).toString();
            String qty = tb.getValueAt(i, 3).toString();
            String u_price = tb.getValueAt(i, 4).toString();
            String t_price = tb.getValueAt(i, 5).toString();

            Statement s = db.mycon().createStatement();
            s.executeUpdate(
                    "INSERT INTO cart (INID, Product_Name, Bar_code, qty, Unit_Price, Total_Price) VALUES ('"
                            + invoice_id + "','" + P_name + "','" + b_code + "','" + qty + "','" + u_price + "','"
                            + t_price + "') ");

        }
        JOptionPane.showMessageDialog(null, "تم الدفع");

    } catch (SQLException e) {
        System.out.println(e);
    }

    try {
        String totqty = total_qty.getText();
        String totbill = total_price.getText();
        String Balance = balance.getText();

        Double tot = Double.valueOf(totbill);
        Double pid = Double.valueOf(paid_amount.getText());
        String status;
        if (pid.equals(0.0)) {
            status = "Non paye";
        } else if (tot > pid) {
            status = "Paye partial";
        } else {
            status = "Paye";
        }
        String inv_id = inid.getText();
        String cname = combo_customer.getSelectedItem().toString();
        Statement ss = db.mycon().createStatement();
        ss.executeUpdate(
                "INSERT INTO sales (INID,cid, Customer_Name, Total_Qty, Total_Bill, Status, Balance,username) VALUES ('"
                        + inv_id + "','" + cus_id + "','" + cname + "','" + totqty + "','" + totbill + "','" + status
                        + "','" + Balance + "','"+uname+"')");

    } catch (NumberFormatException | SQLException e) {
        System.out.println(e);
    }

    try {
        String id = inid.getText();
        Statement s = db.mycon().createStatement();
        s.executeUpdate("UPDATE extra SET val = '" + id + "'WHERE exid = 1 ");
    } catch (SQLException e) {
        System.out.println(e);
    }

//    try {
//        String inv_id = inid.getText(); // Assuming inid is your invoice ID
//        HashMap para = new HashMap();
//        para.put("inv_id", inv_id);
//        try {
//            Class.forName("com.mysql.cj.jdbc.Driver");
//            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/pos", "root", null);
//
//            File f = new File("src/Reports/print.jrxml");
//            JasperReport jr = JasperCompileManager.compileReport(f.getAbsolutePath());
//            JasperPrint jp = JasperFillManager.fillReport(jr, para, con);
//            // Print the report automatically
//            PrintRequestAttributeSet printRequestAttributeSet = new HashPrintRequestAttributeSet();
//            printRequestAttributeSet.add(new Copies(1)); // Number of copies
//            // Print the report to the default printer
//            JasperPrintManager.printReport(jp, false);
//            // Display the receipt on the screen
//            JasperViewer.viewReport(jp, false);
//        } catch (ClassNotFoundException | SQLException | JRException  e) {
//            System.out.println(e);
//        }
//    } catch (Exception e) {
//        System.out.println(e);
//    }

    stckload();}
}

private void combo_customerActionPerformed(java.awt.event.ActionEvent evt) {
    String name = combo_customer.getSelectedItem().toString();
    
    try {
        Statement s = db.mycon().createStatement();
        ResultSet rs = s.executeQuery("SELECT cid,customer_name FROM customers WHERE customer_name ='"+name+"'");
        
        if(rs.next()){
            cus_id = rs.getString("cid");
        }
    }
    catch(SQLException e){
        System.out.println(e);
    }
}

    private void pro_qtyKeyReleased(java.awt.event.KeyEvent evt) {
        calculateProduct();
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addDataToTable();
            resetBarcodeScanner();
    }
}

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        
       
    }//GEN-LAST:event_jButton1KeyPressed

    private void pro_qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_qtyKeyPressed
    
    }//GEN-LAST:event_pro_qtyKeyPressed

    private void combo_productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_combo_productKeyReleased
       
    }//GEN-LAST:event_combo_productKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        //print the bill
        Double tprice = Double.valueOf(total_price.getText());
        if (tprice == 0) {
        JOptionPane.showMessageDialog(paid_amount, "لا يوجد أي سلعة في السلة");
    }
        else{
        printBill();
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balance;
    private javax.swing.JLabel bar_c;
    private javax.swing.JTextField barcode_scanner;
    private javax.swing.JTextArea bill;
    private javax.swing.JComboBox<String> combo_customer;
    private javax.swing.JComboBox<String> combo_product;
    private javax.swing.JLabel inid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField paid_amount;
    private javax.swing.JTextField pro_qty;
    private javax.swing.JLabel stk_qty;
    private javax.swing.JLabel tot_price;
    private javax.swing.JLabel total_price;
    private javax.swing.JLabel total_qty;
    private javax.swing.JLabel unit_price;
    // End of variables declaration//GEN-END:variables
}
